# Generated by Django 3.2.5 on 2021-07-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='nazvanie')),
                ('article_text', models.TextField(verbose_name='text stati')),
                ('pub_date', models.DateTimeField(verbose_name='data pyblikatcii')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='author`s name')),
                ('comment_text', models.CharField(max_length=200, verbose_name='comentarii')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.article')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
